title: Clement Airiohuodion
logo: /github_Images/Clem.jpeg
description: Welcome to My Page
show_downloads: false
theme: jekyll-theme-minimal

# Social media links
social_links:
  linkedin: https://www.linkedin.com/in/yourprofile
  github: https://github.com/Clemobrain
  email: C.O.Airiohuodion@edu.salford.ac.uk

